kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app-dep
  namespace: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      name: notes-app-pod
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: ramkinetic14/notes-app
        ports:
        - containerPort: 80